### ISSUE TITLE
error when buying item

### ISSUE THREAD

**Issue by bbeckann** [renzuzu/renzu_engine#10]
hi bro now i'm trying to use renzu_engine...

when buying the item in the specific store on the map it shows me this error in the console.

![image](https://user-images.githubusercontent.com/95275692/223475054-7386a3ee-0ecf-420b-a647-0f44b2237070.png)

![image](https://user-images.githubusercontent.com/95275692/223472546-9fd93224-28e6-4e86-a7a8-28da6fc3a38d.png)

**Comment by renzuzu** [comment]
fix , thank you

**Comment by bbeckann** [comment]
![image](https://user-images.githubusercontent.com/95275692/225220286-26b71f61-9d92-4a9c-8b9c-a141a7a0e771.png)
I just updated to a new version, it gives this error.
